# Site
repository: yusufkoca/yusufkoca.github.io
favicon: images/favicon.ico

# Personal info
name: Yusuf Koca
title: JavaScript Developer
email: yfkoca@yandex.com
website: www.yusufkoca.dev

# Social links
# twitter_username: facespics
github_username: yusufkoca
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ysfkoca
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profilkare.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yusuf. I like to call myself a JavaScript Developer which I have experience and interest in learning new things about it. 
  I currently work as a Frontend Developer.

  I am most skilled in: <mark>JavaScript</mark> <mark>TypeScript</mark> and <mark>React.js</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Enough technical
more_content: | # this will include new lines to allow paragraphs
  32 years old world citizen without a passport. I currently live in Ankara, Turkey with my dearest wife. 
  I grow up in Denizli which I'm proud of for no reason. 

  Things I enjoy doing and/or talking about:
   - Comics (Huge Batman Fan!)
   - Board Games
   - Smart Home
   - Investing
   - Basketball
   - History

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
